#!/usr/bin/env python3
"""Generate docker-compose.yml for GLPI multi-version test environment.

Usage:
    python3 generate-compose.py > docker-compose.yml

To add a new GLPI version, append its patch number to VERSIONS_10X or VERSIONS_11X.
"""
import sys

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

# ── Version configuration ─────────────────────────────────────────────────────
VERSIONS_10X = [18, 19, 20, 21, 22, 23, 24, 25, 26]   # 10.0.X patch numbers
VERSIONS_11X = [0, 1, 2, 3, 4, 5, 6, 7, 8]            # 11.0.X patch numbers

# ── Credentials ───────────────────────────────────────────────────────────────
DB_ROOT_PASS = "rootpassword"
DB_NAME      = "glpi"
DB_USER      = "glpi"
DB_PASS      = "glpipassword"

# ── MySQL healthcheck — gives up to 120s for MySQL to initialise ──────────────
MYSQL_HEALTHCHECK = {
    "test": ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"],
    "interval": "5s",
    "timeout": "3s",
    "retries": 24,
    "start_period": "10s",
}


def make_pair(major: int, patch: int) -> dict:
    slug    = f"{major}_0_{patch}"
    ver     = f"{major}.0.{patch}"
    port    = major * 1000 + patch   # 10.0.18 → 10018, 11.0.7 → 11007
    db_svc  = f"mysql_{slug}"
    app_svc = f"glpi_{slug}"
    net     = f"glpi_net_{slug}"

    mysql_service = {
        "image": "mysql:8.0",
        "container_name": f"glpi_mysql_{slug}",
        "environment": {
            "MYSQL_ROOT_PASSWORD": DB_ROOT_PASS,
            "MYSQL_DATABASE": DB_NAME,
            "MYSQL_USER": DB_USER,
            "MYSQL_PASSWORD": DB_PASS,
        },
        "volumes": [f"mysql_data_{slug}:/var/lib/mysql"],
        "healthcheck": MYSQL_HEALTHCHECK,
        "restart": "unless-stopped",
        "networks": [net],
    }

    env = {
        "GLPI_DB_HOST": db_svc,
        "GLPI_DB_PORT": "3306",
        "GLPI_DB_NAME": DB_NAME,
        "GLPI_DB_USER": DB_USER,
        "GLPI_DB_PASSWORD": DB_PASS,
        # 10.x install.sh: [[ -z "$GLPI_SKIP_AUTOUPDATE" ]] — non-empty disables update
        # 11.x install.sh: ! $GLPI_SKIP_AUTOUPDATE     — "true" command exits 0, !0=false → no update
        "GLPI_SKIP_AUTOUPDATE": "true",
    }
    if major == 10 and patch == 18:
        # 10.0.18 is the only version whose install.sh uses the old-style check:
        #   [[ -z "$GLPI_SKIP_AUTOINSTALL" ]]
        # Image default "false" is non-empty → -z "false" = false → install SKIPPED.
        # Setting "" (empty) makes -z "" = true → install RUNS.
        #
        # All other versions (10.0.19+, 11.x) use the new-style check:
        #   ! $GLPI_SKIP_AUTOINSTALL   (value treated as a shell command)
        # Image default "false" → bash `false` exits 1 → !1=0 → install RUNS automatically.
        # Setting "" there would break it (empty command is undefined behavior), so we leave
        # GLPI_SKIP_AUTOINSTALL unset for those and let the image default do the right thing.
        env["GLPI_SKIP_AUTOINSTALL"] = ""

    glpi_service = {
        "image": f"glpi/glpi:{ver}",
        "container_name": f"glpi_{slug}",
        "ports": [f"127.0.0.1:{port}:80"],
        "environment": env,
        "volumes": [f"glpi_data_{slug}:/var/glpi"],
        "depends_on": {db_svc: {"condition": "service_healthy"}},
        "restart": "unless-stopped",
        "networks": [net],
    }

    return {
        "services": {db_svc: mysql_service, app_svc: glpi_service},
        "volumes":  {f"mysql_data_{slug}": {}, f"glpi_data_{slug}": {}},
        "networks": {net: {"driver": "bridge"}},
    }


def build() -> dict:
    services: dict = {}
    volumes:  dict = {}
    networks: dict = {}

    for major, patches in [(10, VERSIONS_10X), (11, VERSIONS_11X)]:
        for patch in patches:
            chunk = make_pair(major, patch)
            services.update(chunk["services"])
            volumes.update(chunk["volumes"])
            networks.update(chunk["networks"])

    return {"services": services, "volumes": volumes, "networks": networks}


if __name__ == "__main__":
    compose = build()
    print("# Generated by generate-compose.py — do not edit manually")
    print("# To regenerate: python3 generate-compose.py > docker-compose.yml")
    print(yaml.dump(compose, default_flow_style=False, sort_keys=False), end="")

    total_versions = len(VERSIONS_10X) + len(VERSIONS_11X)
    print(f"\nGenerated {total_versions} GLPI instances ({total_versions * 2} containers total):", file=sys.stderr)
    print(f"  10.x  ports: 10{VERSIONS_10X[0]:03d}–10{VERSIONS_10X[-1]:03d}  (GLPI 10.0.{VERSIONS_10X[0]}–10.0.{VERSIONS_10X[-1]})", file=sys.stderr)
    print(f"  11.x  ports: 11{VERSIONS_11X[0]:03d}–11{VERSIONS_11X[-1]:03d}  (GLPI 11.0.{VERSIONS_11X[0]}–11.0.{VERSIONS_11X[-1]})", file=sys.stderr)
    print("\nStart:  podman compose up -d", file=sys.stderr)
    print("Login:  glpi / glpi", file=sys.stderr)
